{"name": "Тест на создание фейковых данных", "status": "broken", "statusDetails": {"message": "AttributeError: 'Database' object has no attribute 'test_create_fake_products'. Did you mean: 'test_create_fake_data'?", "trace": "@allure.title(\"Тест на создание фейковых данных\")\n    def test_create_fake_data():\n        # Используем методы объекта db для создания фейковых данных\n>       db.test_create_fake_products(count=2)\nE       AttributeError: 'Database' object has no attribute 'test_create_fake_products'. Did you mean: 'test_create_fake_data'?\n\napi_test.py:16: AttributeError"}, "start": 1703592687266, "stop": 1703592687266, "uuid": "fe2fa3f9-44a6-4482-aa30-ff0b18c9c2f2", "historyId": "b355e833ec90965f54a795af8b707372", "testCaseId": "b355e833ec90965f54a795af8b707372", "fullName": "api_test#test_create_fake_data", "labels": [{"name": "suite", "value": "api_test"}, {"name": "host", "value": "DESKTOP-TV6CGIP"}, {"name": "thread", "value": "10180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}