{"name": "Тест на создание фейковых данных", "status": "broken", "statusDetails": {"message": "AttributeError: 'Database' object has no attribute 'test_create_fake_products'. Did you mean: 'test_create_fake_users'?", "trace": "@allure.title(\"Тест на создание фейковых данных\")\n    def test_create_fake_data():\n        # Используем методы объекта db для создания фейковых данных\n        db.test_create_fake_users(2)\n>       db.test_create_fake_products(2)\nE       AttributeError: 'Database' object has no attribute 'test_create_fake_products'. Did you mean: 'test_create_fake_users'?\n\napi_test.py:17: AttributeError"}, "start": 1703592091561, "stop": 1703592091564, "uuid": "9d12beee-c8c5-4029-ab0b-878ad50c3fde", "historyId": "b355e833ec90965f54a795af8b707372", "testCaseId": "b355e833ec90965f54a795af8b707372", "fullName": "api_test#test_create_fake_data", "labels": [{"name": "suite", "value": "api_test"}, {"name": "host", "value": "DESKTOP-TV6CGIP"}, {"name": "thread", "value": "9324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}